### PR TITLE
fix: header and footer on login page (#22)

### LINKED ISSUE #22: Make Header and Footer not show on Login Page
make better layout implementation that can be remove at someplace for example login page, and maybe register in the future

### PR DESCRIPTION
**Pull request by LordAldi**
fixes #22 
-fix header and footer on login page
-add react-router-dom for better routing

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -1,26 +1,19 @@
 import React from "react";
-import { Router } from "@reach/router";
-import { Layout } from "antd";
-
-import Header from "./components/header/Header";
-import Footer from "./components/footer/Footer";
 import { Home, Login } from "./pages";
-
-const { Content } = Layout;
+import { BrowserRouter, Route, Switch } from "react-router-dom";
```
Comment (ariefrahmansyah) [inline src/App.js]: I prefer to use `@reach/router` instead of `react-router-dom`. You can refer to this post: https://reacttraining.com/blog/reach-react-router-future/

Unless you have strong opinion on using `react-router-dom`, I open to your suggestion.

**Review by ariefrahmansyah — CHANGES_REQUESTED** [review]

File: src/App.js (hunk 1 above)
Comment (LordAldi) [reply src/App.js]: Tbh, i just use it because i always use it. I will try change it

File: yarn.lock [hunk 2]
```diff
@@ -12532,6 +12564,35 @@ react-refresh@^0.8.3:
   resolved "https://registry.yarnpkg.com/react-refresh/-/react-refresh-0.8.3.tgz#721d4657672d400c5e3c75d063c4a85fb2d5d68f"
   integrity sha512-X8jZHc7nCMjaCqoU+V2I0cOhNW+QMBwSUkeXnTi8IPe6zaRWfn60ZzvFDZqWPfmSJfjub7dDW1SP0jaHWLu/hg==
 
+react-router-dom@^5.2.0:
```
Comment (ariefrahmansyah) [inline yarn.lock]: Please re-run `yarn` so these dependencies got removed.

**Review by ariefrahmansyah — CHANGES_REQUESTED** [review]

**Review by ariefrahmansyah — APPROVED** [review]
LGTM

**Review by fadelarmando — APPROVED** [review]
LGTM
